import re
import shutil
from pathlib import Path

from setuptools import setup, find_packages


VERSION = {}  # type: ignore
with open("dooly/__version__.py", "r") as version_file:
    exec(version_file.read(), VERSION)


# Remove stale dooly.egg-info directory to avoid https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "transformers.egg-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "If you recently updated dooly, this is expected,\n"
            "but it may prevent transformers from installing in editable mode.\n\n"
            "This directory is automatically generated by Python's packaging tools.\n"
            "I will remove it now.\n\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)


_deps = [
    "black~=22.0",
    "flake8>=3.8.3",
    "dataclasses",
    "datasets",
    "numpy>=1.17",
    "fugashi>=1.0",
    "filelock",
    "huggingface-hub>=0.1.0,<1.0",
    "importlib_metadata",
    "jieba",
    "requests",
    "regex",
    "packaging>=20.0",
    "pyyaml>=5.1",
    "mecab",
    "pororo",
    "boto3",
    "whoosh",
    "ipadic>=1.0.0,<2.0",
    "tqdm>=4.27",
    "torch>=1.0",
    "tokenizers>=0.11.1,!=0.11.3",
    "transformers>=4.8.2",
]

deps = {b: a for a, b in (re.findall(r"^(([^!=<>~]+)(?:[!=<>~].*)?$)", x)[0] for x in _deps)}


def deps_list(*pkgs):
    return [deps[pkg] for pkg in pkgs]


extras = {}
extras["ja"] = deps_list("fugashi", "ipadic")
extras["zh"] = deps_list("jieba")
extras["mecab"] = deps_list("mecab")
extras["search"] = deps_list("whoosh")
extras["convert"] = deps_list("pororo", "boto3")
extras["quality"] = deps_list("black", "flake8")

extras["all"] = (
    extras["ja"]
    + extras["zh"]
    + extras["mecab"]
    + extras["search"]
    + extras["convert"]
    + extras["quality"]
)

install_requires = [
    deps["dataclasses"] + ";python_version<'3.7'",  # dataclasses for Python versions that don't have it
    deps["filelock"],  # filesystem locks, e.g., to prevent parallel downloads
    deps["huggingface-hub"],
    deps["datasets"],
    deps["numpy"],
    deps["torch"],
    deps["packaging"],  # utilities from PyPA to e.g., compare versions
    deps["pyyaml"],  # used for the model cards metadata
    deps["regex"],  # for OpenAI GPT
    deps["requests"],  # for downloading models over HTTPS
    deps["tokenizers"],
    deps["tqdm"],  # progress bars in model download and training scripts
]


setup(name='dooly',
      version=VERSION["version"],
      url='https://github.com/jinmang2/DOOLY',
      author='jinmang2',
      author_email='jinmang2@gmail.com',
      description='A library that handles everything with 🤗 and supports batching to models in PORORO',
      python_requires=">=3.6.0",
      packages=find_packages(exclude=['tests', 'convert_scripts']),
      long_description=open('README.md', encoding="utf-8").read(),
      long_description_content_type='text/markdown',
      extras_require=extras,
      install_requires=install_requires,
      zip_safe=False,
      classifiers=[
          "Operating System :: OS Independent",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.6",
          "Programming Language :: Python :: 3.7",
          "Programming Language :: Python :: 3.8",
          "Programming Language :: Python :: 3.9",
          "License :: OSI Approved :: Apache Software License",
      ],
)
