from .machine_reading_comprehension import MachineReadingComprehension
from .machine_translation import MachineTranslation
from .named_entity_recognition import NamedEntityRecognition
from .natural_language_inference import NaturalLanguageInference
from .word_sense_disambiguation import WordSenseDisambiguation
from .zero_shot_classification import ZeroShotClassification
